<?php
namespace EENE\ExtractionBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use EENE\ExtractionBundle\Entity\TextFile;
/**
 * TextFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextFileRepository extends EntityRepository
{

         //créer 1 Text file (sur serveur et BD) pour la fonctionalité upload de fichier(s)
    public function createTextFileForUpload($uploadedFile,$user)
    {
          // $user= $this->getUser();
                   $textfile= new TextFile();
                   $textfile->setCreatedAt(new \DateTime());
                   $textfile->setSize($uploadedFile->getClientSize());
                   $textfile->setName($uploadedFile->getClientOriginalName());
                   $textfile->setUser($user);
                   $uploadedFile->move($user->getUploadUserDir(), $uploadedFile->getClientOriginalName());
                   //insert text file in database
                   $em = $this->getEntityManager();
                   $em->persist($textfile);
                   $em->flush();
                return $textfile;
    }
    
     //créer 1 Text file (sur serveur et BD) pour la fonctionalité analyse de texte
    public function createTextFileForAnalyze($textfilename,$data,$user)
    {
                
                   $textfile= new TextFile();
                   $textfile->setCreatedAt(new \DateTime());
                   $textfile->setName($textfilename);
                   $textfile->setUser($user);
                    //créer fichier Text en serveur 
                   file_put_contents($user->getUploadUserDir().'/'.$textfilename, $data);
                   //créer fichier Text  en BD
                   $em = $this->getEntityManager();
                   $em->persist($textfile);
                   $em->flush();
                return $textfile;
    }
   
}
